### ISSUE TITLE
Go to definition is called when there is no other highlights

### ISSUE THREAD

**Issue by tjx666** [zardoy/vscode-highlight-utils#2]
For now, the command `Highlight Utils: Go to Highlighted Locations` seems to behavior like `Go to Definition`

https://user-images.githubusercontent.com/41773861/216001956-d4cac27f-f1b5-4401-89d6-952ff97d6f56.mov

**Comment by zardoy** [comment]
Hi! Thanks for the issue, after some debugging I figured out that public api for peeking provided locations executes go to definition command when there is no other location. This seems to be fixed in upcoming vscode release, but I'll provide adiitional fix with message anyway.

So this is happening only when there is single highlight in document, I'll drop there and print message instead.

**Comment by tjx666** [comment]
I think it would be more useful this plugin can peek vue component tag like other variables.
For now, there is no good method to get Vue Component import place
@zardoy

**Comment by zardoy** [comment]
> For now, there is no good method to get Vue Component import place

In case of volar in you can use *Go to References* to go to component import. Probably its Volar bug that it doesn't highlight other locations as it should

**Comment by tjx666** [comment]
> Probably its Volar bug that it doesn't highlight other locations as it should

@johnsoncodehk
